### ISSUE TITLE
Recipes are not working 

### ISSUE THREAD

**Issue by kacperowski2** [sigonasr2/MCRandomizer#7]
Recipes are not working and server console is dropping errors

**Comment by sigonasr2** [comment]
Please provide a full server log of the messages. Are you certain you are using Bukkit/Spigot version 1.14.2?

**Comment by sigonasr2** [comment]
When using this plugin please include both furnace_data and recipe_data files in the plugin base directory (where all other plugin files are stored). These are required files that define recipes for the plugin to randomize.

This is not documented due to this plugin only being for my personal use. I have no intention of others using it.

**Comment by kacperowski2** [comment]
[12:35:59] [Server thread/ERROR]: Error occurred while enabling MCRandomizer v1.0.0 (Is it up to date?)
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_201]
        at scramble.plugin.Template.onEnable(Template.java:389) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

I include both files and not working

**Comment by sigonasr2** [comment]
Please verify both of the files are in the same directory as files as server.properties, bukkit.yml, etc.

This error occurs because there are no items to load, due to not finding a file. Please post again if you still have issues.

**Comment by kacperowski2** [comment]
Plguin works but i cant craft plank(from oak i have glass)

**Comment by sigonasr2** [comment]
It's a randomizer. The only guaranteed recipe is a crafting table.
